version: '3.9'
networks:
    test:
services:
  
  Backend:
    container_name: express_bkend
    image: expressimg
    build:
        context: ./express-app
        dockerfile: Dockerfile
    depends_on:
      - mongodb

  
  

    tty: true
    ports:
      - 7050:8090
  mongodb:
    image: mongo:latest
    container_name: mongodb
    
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
    #  - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    #   - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/dir 
      
volumes:
  mongo_volume:
  